# Generated by Django 3.1.3 on 2022-05-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_choice_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='is_right',
        ),
    ]
