# Generated by Django 3.1.3 on 2022-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20220505_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_right',
            new_name='is_correct',
        ),
    ]
